### ISSUE TITLE
Cells not showing in run

### ISSUE THREAD

**Issue by christina-zhou-96** [LauraHannah44/Game-Of-Life#1]
Hello!

I liked your idea a lot :+1: 

I tried to run the main file, but nothing happened. It was a black screen, except for the frames #s ticking away in white in the corner.

I tried toggling COLOUR to false, but unfortunately it didn't do anything.

Anyway, I love your idea, keep it up!

**Comment by laurapigeon** [comment]
Ah! Thank you, I didn't think anyone would find it so I didn't make a
controls file. I'll do that now then!

At first the file is in kind of standby, you can populate the board using
number keys or some letters.

**Comment by christina-zhou-96** [comment]
Awesome - look forward to it - Conway just died of coronavirus if you haven't heard, so this is timely =/
